### PR TITLE
Add contact

### PR DESCRIPTION
**Pull request by sluceno**
Hi!

I am working in the add_contact functionality. I just wanted to let you know. I did my first workarrounds.

Actually is working right now, but I have to dig more into it.

Any advice is welcome

### CODE REVIEW

**Comment by jiren** [comment]
Hi Sluceno,

Thanks for pull request 

Updates:
I am planning to write down telegram in pure ruby because there are following problems
- event timers to execute queries so we have to call every time `net_connection`
- c code(Telegram cli code) is not thread safe because of extern variables.

**Comment by sluceno** [comment]
Hey Jiren, you’re welcome! 

I didn’t expect you would merge the branch so quickly. I wanted to iterate again over it, because it was my first approach and I could not test 100% what I’ve done. I will do it along this week.

I saw that some methods has many calls to net_connection that I did not understand why, so those are the problems you found.

If you need some help on writting down telegram in ruby, I can try to help you. I am not a ruby expert, since I switched to ruby a year ago, but I am motivated on doing things.
-- 
Sergio Luceno

On 9 Apr 2014 at 07:54:14, Jiren Patel (notifications@github.com) wrote:

Hi Sluceno,

Thanks for pull request

I am planning to write down telegram in pure ruby because there are following problems

event timers to execute queries so we have to call every time net_connection
c code(Telegram cli code) is not thread safe because of extern variables.

**Comment by jiren** [comment]
Dont't worry about pull request merge. Currently gem is not released and it is still under development that's why i have merger branch so if any errors come then we can fix it.

To check it is correctly compiling you can run `rake compile` and to run test gem run just `rake` - it has default task to clean compile and run test cases.

For ruby implementation I have write some code for serialization and de-serialisation in lib and respective test cases. We can start from using this code.

**Comment by mllocs** [comment]
:clap:

**Pull request merged**
